function show(message,type){let el=document.getElementById('result');el.className='notice '+(type||'');el.textContent=message}
function messageFor(error){return({email_not_verified:'Confirm your email, then return to this page and sign in.',invitation_email_mismatch:'This invitation was sent to a different email address.',invitation_already_used:'This invitation has already been used.',invitation_revoked:'This invitation was revoked by the fleet manager.',invitation_expired:'This invitation expired. Ask the manager for a new link.',invalid_invitation:'This invitation link is invalid.',driver_already_assigned:'This driver account already belongs to another fleet.',driver_profile_required:'Your driver profile could not be created.',sign_in_required:'Sign in with the invited email first.'})[error]||'The invitation could not be accepted. Please try again.'}
function token(){return sessionStorage.getItem('occulert-invite-token')||''}
function setAuthBusy(busy){let form=document.getElementById('acceptForm');form.setAttribute('aria-busy',String(busy));form.querySelectorAll('button').forEach(button=>{button.disabled=busy||button.dataset.rateLimited==='true'})}
function renderUser(){let user=window.OcculertBackend.currentUser(),hasToken=!!token(),email=document.getElementById('email'),password=document.getElementById('password');if(!hasToken){document.getElementById('acceptForm').classList.add('hidden');document.getElementById('userState').className='notice bad';document.getElementById('userState').textContent='This invitation link is missing or invalid.';return}if(user){email.value=user.email||'';email.readOnly=true;password.required=false;document.getElementById('emailField').classList.add('hidden');document.getElementById('passwordField').classList.add('hidden');document.getElementById('signedOutActions').classList.add('hidden');document.getElementById('accountHelp').classList.add('hidden');document.getElementById('accountRecoveryActions').classList.add('hidden');document.getElementById('signedInActions').classList.remove('hidden');document.getElementById('userState').textContent='Signed in as '+(user.email||'your Occulert account')+'.';}else{email.readOnly=false;password.required=true;document.getElementById('emailField').classList.remove('hidden');document.getElementById('passwordField').classList.remove('hidden');document.getElementById('signedOutActions').classList.remove('hidden');document.getElementById('accountHelp').classList.remove('hidden');document.getElementById('accountRecoveryActions').classList.remove('hidden');document.getElementById('signedInActions').classList.add('hidden');document.getElementById('userState').textContent='Sign in or create a driver account with the invited email.'}}
async function finishAcceptance(){show('Verifying your invitation…');let profile=await window.OcculertBackend.ensureDriverProfile({name:document.getElementById('name').value.trim(),vehicle:document.getElementById('vehicle').value.trim()});if(!profile.ok){show(messageFor(profile.body&&profile.body.error),'bad');return}let result=await window.OcculertBackend.acceptFleetInvitation(token());if(!result.ok){show(messageFor(result.body&&result.body.error),'bad');return}sessionStorage.removeItem('occulert-invite-token');document.getElementById('acceptForm').classList.add('hidden');document.getElementById('successActions').classList.remove('hidden');show('You joined '+(result.body.fleet.company_name||'the fleet')+'. Your future opted-in sessions can now appear in its protected dashboard.','good')}
function invitationFormValid(){let name=document.getElementById('name');name.value=name.value.trim();return document.getElementById('acceptForm').reportValidity()}
async function acceptForCurrentUser(){if(!invitationFormValid())return;setAuthBusy(true);try{await finishAcceptance()}catch(error){show('Occulert could not finish the invitation. Check your connection and try again.','bad')}finally{setAuthBusy(false)}}
function useDifferentAccount(){window.OcculertBackend.signOut();show('Signed out. Use the invited email to continue.');renderUser()}
async function resendConfirmation(){let emailField=document.getElementById('email');if(!emailField.reportValidity())return;setAuthBusy(true);try{show('Requesting a new confirmation email…');let result=await window.OcculertBackend.resendSignupConfirmation(emailField.value.trim());if(!result.ok){if(window.OcculertBackend.isEmailRateLimited(result))document.getElementById('resendConfirmationBtn').dataset.rateLimited='true';show(window.OcculertBackend.resendConfirmationMessage(result),'bad');return}show('If an unconfirmed Occulert account uses that email, a new confirmation message is on the way. Check Inbox and Spam.','good')}catch(error){show('Occulert could not reach the account service. Check your connection and try again.','bad')}finally{setAuthBusy(false)}}
async function signInAndAccept(event,mode){event.preventDefault();if(!invitationFormValid())return;setAuthBusy(true);try{show(mode==='signup'?'Creating your account…':'Signing in…');let email=document.getElementById('email').value.trim(),password=document.getElementById('password').value;let auth=mode==='signup'?await window.OcculertBackend.signUp(email,password):await window.OcculertBackend.signIn(email,password);if(!auth.ok){let message=window.OcculertBackend.authMessage(auth,mode);if(window.OcculertBackend.isEmailRateLimited(auth))document.getElementById('createAccountBtn').dataset.rateLimited='true';if(window.OcculertBackend.needsSignupConfirmation(auth))document.getElementById('resendConfirmationBtn').classList.remove('hidden');show(message,'bad');return}if(!window.OcculertBackend.currentUser()){document.getElementById('resendConfirmationBtn').classList.remove('hidden');show('Confirmation required. Check Inbox and Spam. If no message arrives, select Resend Confirmation once. If this address already has an account, use Sign In or Forgot Password.','good');return}renderUser();await finishAcceptance()}catch(error){show('Occulert could not reach the sign-in service. Check your connection and try again.','bad')}finally{setAuthBusy(false)}}
renderUser();
