function readDrivers(){try{const value=JSON.parse(localStorage.getItem('occulert-drivers')||'[]');return Array.isArray(value)?value:null}catch(e){return null}}
function validDriver(x){return x&&typeof x==='object'&&typeof x.id==='string'&&x.id&&typeof x.name==='string'&&x.name.trim()}
function get(){return(readDrivers()||[]).filter(validDriver)}
function mutableDrivers(){const drivers=readDrivers();if(!drivers)alert('Saved profiles could not be read. Your stored data has been kept. Restore browser storage access before making changes.');return drivers}
function set(v){try{localStorage.setItem('occulert-drivers',JSON.stringify(v));return true}catch(e){alert('Your changes could not be saved in this browser. Check available storage and try again.');return false}}
function createDriverId(){try{if(globalThis.crypto&&typeof globalThis.crypto.randomUUID==='function')return'DRV-'+globalThis.crypto.randomUUID()}catch(e){}return'DRV-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2)}
function initials(n){return(n||'D').split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase()}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function render(){let d=get();document.getElementById('drivers').innerHTML=d.length?d.map(x=>`<div class="driver"><div class="avatar">${esc(initials(x.name))}</div><div><strong>${esc(x.name)}</strong><br><span class="muted">${esc(x.route||'No route set')}</span></div><div><span class="pill ${x.status==='Inactive'?'danger':''}">${esc(x.status||'Active')}</span><br><button class="btn" style="margin-top:8px;padding:6px 9px" data-driver-id="${esc(x.id)}" onclick="removeDriver(this.dataset.driverId)">Remove</button></div></div>`).join(''):'<p class="muted">No drivers yet.</p>'}
function addDriver(){let name=document.getElementById('name').value.trim();if(!name)return alert('Add a driver name');let route=document.getElementById('route').value.trim(),status=document.getElementById('status').value,d=mutableDrivers();if(!d)return;d.unshift({id:createDriverId(),name,route,status,createdAt:new Date().toISOString()});if(!set(d))return;document.getElementById('name').value='';document.getElementById('route').value='';render()}
function removeDriver(id){let d=mutableDrivers();if(!d)return;let index=d.findIndex(x=>validDriver(x)&&x.id===id);if(index<0){render();return}d.splice(index,1);if(set(d))render()}
function seedDrivers(){const drivers=mutableDrivers();if(!drivers)return;if(drivers.length&&!confirm('Replace the local driver profiles with sample drivers?'))return;if(set([{id:'DRV-1',name:'Marcus T.',route:'North Bay Delivery Route',status:'Active'},{id:'DRV-2',name:'Jordan M.',route:'Bay Bridge Eastbound',status:'Active'},{id:'DRV-3',name:'Alicia S.',route:'Oakland Delivery Loop',status:'Training'}]))render()}
render();
