let currentFleet=null;
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function showPage(message,type){let el=document.getElementById('pageStatus');el.className='notice '+(type||'');el.textContent=message}
function showInvite(message,type){let el=document.getElementById('inviteStatus');el.className='notice '+(type||'');el.textContent=message}
function messageFor(error){return({email_not_verified:'Confirm your email, then sign in again.',invalid_company_name:'Enter a company or fleet name.',invalid_email:'Enter a valid driver email.',cannot_invite_self:'Use a different email for the driver.',active_invitation_exists:'A current invitation already exists for that email.',too_many_pending_invitations:'Revoke unused invitations before creating more.',invitation_rate_limited:'Too many invitations were created recently. Wait about an hour and try again.',resend_too_soon:'Wait one minute before sending a new link.',invitation_not_found:'That pending invitation is no longer available.',invitation_not_pending:'That invitation is no longer pending.',sign_in_required:'Sign in as the fleet owner first.'})[error]||'The request could not be completed. Please try again.'}
function inviteStatus(invite){if(invite.accepted_at)return['Accepted','accepted'];if(invite.revoked_at)return['Revoked','closed'];if(Date.parse(invite.expires_at)<=Date.now())return['Expired','closed'];return['Pending','pending']}
function renderInvitations(invitations){let list=document.getElementById('inviteList');if(!invitations.length){list.innerHTML='<div class="notice">No invitations yet.</div>';return}list.innerHTML=invitations.map(i=>{let state=inviteStatus(i),pending=state[0]==='Pending',id=encodeURIComponent(i.id);return `<div class="invite"><div><strong>${esc(i.email)}</strong><div class="status">Created ${esc(new Date(i.created_at).toLocaleString())} · Expires ${esc(new Date(i.expires_at).toLocaleString())}</div><span class="pill ${state[1]}">${state[0]}</span></div>${pending?`<div class="invite-actions"><button class="btn" onclick="resendInvite('${id}')">Send New Link</button><button class="btn danger" onclick="revokeInvite('${id}')">Revoke</button></div>`:''}</div>`}).join('')}
async function loadInvitations(){let result=await window.OcculertBackend.listFleetInvitations();if(result.ok)renderInvitations(result.body.invitations||[]);else renderInvitations([])}
function showFleet(fleet){currentFleet=fleet;document.getElementById('createCard').classList.add('hidden');document.getElementById('inviteCard').classList.remove('hidden');document.getElementById('listCard').classList.remove('hidden');document.getElementById('fleetName').textContent='Invite drivers to '+fleet.company_name;showPage('Signed in as the verified owner of '+fleet.company_name+'.','good');loadInvitations()}
async function createFleet(event){event.preventDefault();showPage('Creating your protected fleet…');let result=await window.OcculertBackend.createFleet(document.getElementById('companyName').value.trim());if(result.ok)showFleet(result.body.fleet);else showPage(messageFor(result.body&&result.body.error),'bad')}
function setInviteBusy(busy){document.getElementById('inviteCard').setAttribute('aria-busy',String(busy));document.querySelectorAll('#inviteCard button,#inviteList button').forEach(button=>button.disabled=busy)}
function showNewInvitation(result,renewed){let invitation=result.body.invitation,path=invitation.accept_path,link=new URL(path,window.location.origin).href,email=invitation.email,subject='Join '+currentFleet.company_name+' on Occulert',body='You are invited to join '+currentFleet.company_name+' on Occulert.\n\nOpen this one-time link with '+email+':\n'+link+'\n\nThe link expires in seven days.';document.getElementById('inviteLink').value=link;document.getElementById('emailInvite').href='mailto:'+encodeURIComponent(email)+'?subject='+encodeURIComponent(subject)+'&body='+encodeURIComponent(body);document.getElementById('inviteLinkBox').classList.remove('hidden');showInvite((renewed?'A fresh one-time link was created. ':'Invite created. ')+'Choose Email Link or Copy Link; it will not be shown again.','good')}
async function createInvite(event){event.preventDefault();setInviteBusy(true);try{showInvite('Creating a one-time invitation…');document.getElementById('inviteLinkBox').classList.add('hidden');let result=await window.OcculertBackend.createFleetInvitation(document.getElementById('driverEmail').value.trim());if(!result.ok){showInvite(messageFor(result.body&&result.body.error),'bad');return}showNewInvitation(result,false);document.getElementById('driverEmail').value='';await loadInvitations()}finally{setInviteBusy(false)}}
async function resendInvite(encodedId){let id;try{id=decodeURIComponent(encodedId)}catch(e){return}setInviteBusy(true);try{showInvite('Revoking the old link and creating a fresh invitation…');document.getElementById('inviteLinkBox').classList.add('hidden');let result=await window.OcculertBackend.resendFleetInvitation(id);if(!result.ok){showInvite(messageFor(result.body&&result.body.error),'bad');return}showNewInvitation(result,true);await loadInvitations()}finally{setInviteBusy(false)}}
async function revokeInvite(encodedId){let id;try{id=decodeURIComponent(encodedId)}catch(e){return}setInviteBusy(true);try{let result=await window.OcculertBackend.revokeFleetInvitation(id);showInvite(result.ok?'Invitation revoked.':messageFor(result.body&&result.body.error),result.ok?'good':'bad');await loadInvitations()}finally{setInviteBusy(false)}}
async function copyInvite(){let input=document.getElementById('inviteLink');try{await navigator.clipboard.writeText(input.value);showInvite('Invitation link copied.','good')}catch(e){input.select();document.execCommand('copy');showInvite('Invitation link copied.','good')}}
async function boot(){let user=window.OcculertBackend.currentUser();if(!user){showPage('Sign in as a fleet manager to create or manage a fleet.','bad');return}let result=await window.OcculertBackend.getFleet();if(result.ok){showFleet(result.body.fleet);return}if(result.status===404){document.getElementById('createCard').classList.remove('hidden');showPage('Signed in. Create your fleet to begin inviting drivers.');return}showPage(messageFor(result.body&&result.body.error),'bad')}
boot();
