(function(root){
'use strict';
function invoke(name,...args){const handler=root[name];if(typeof handler==='function')return Reflect.apply(handler,root,args)}
const routes={
"/accept-invite.html":Object.freeze({"acceptForCurrentUser":{type:"click",call:(element,event)=>{invoke('acceptForCurrentUser')}},"resendConfirmation":{type:"click",call:(element,event)=>{invoke('resendConfirmation')}},"signInAndAccept-event-signin":{type:"submit",call:(element,event)=>{invoke('signInAndAccept',event,'signin')}},"signInAndAccept-event-signup":{type:"click",call:(element,event)=>{invoke('signInAndAccept',event,'signup')}},"useDifferentAccount":{type:"click",call:(element,event)=>{invoke('useDifferentAccount')}}}),
"/account.html":Object.freeze({"changeEmail-event":{type:"submit",call:(element,event)=>{invoke('changeEmail',event)}},"changePassword-event":{type:"submit",call:(element,event)=>{invoke('changePassword',event)}},"deleteAccount-event":{type:"submit",call:(element,event)=>{invoke('deleteAccount',event)}},"registerPasskey":{type:"click",call:(element,event)=>{invoke('registerPasskey')}},"retryPasskeySetup":{type:"click",call:(element,event)=>{invoke('retryPasskeySetup')}},"saveProfile-event":{type:"submit",call:(element,event)=>{invoke('saveProfile',event)}},"signOut":{type:"click",call:(element,event)=>{invoke('signOut')}}}),
"/app.html":Object.freeze({"closeIOSInstallModal":{type:"click",call:(element,event)=>{invoke('closeIOSInstallModal')}},"dismissBreak":{type:"click",call:(element,event)=>{invoke('dismissBreak')}},"exportCSV":{type:"click",call:(element,event)=>{invoke('exportCSV')}},"toggleVoice":{type:"click",call:(element,event)=>{invoke('toggleVoice')}},"triggerPWAInstall":{type:"click",call:(element,event)=>{invoke('triggerPWAInstall')}}}),
"/driver-profiles.html":Object.freeze({"addDriver":{type:"click",call:(element,event)=>{invoke('addDriver')}},"removeDriver":{type:"click",call:(element,event)=>{invoke('removeDriver',element.dataset.driverId)}},"seedDrivers":{type:"click",call:(element,event)=>{invoke('seedDrivers')}}}),
"/fleet-dashboard.html":Object.freeze({"queueDriverListRender-input":{type:"input",call:(element,event)=>{invoke('queueDriverListRender')}},"clearDemoData":{type:"click",call:(element,event)=>{invoke('clearDemoData')}},"copy-driver":{type:"click",call:(element,event)=>{invoke('copyDriver',element.dataset.driverArg)}},"copyOpsSummary":{type:"click",call:(element,event)=>{invoke('copyOpsSummary')}},"exportFleetCSV":{type:"click",call:(element,event)=>{invoke('exportFleetCSV')}},"exportPilotReport":{type:"click",call:(element,event)=>{invoke('exportPilotReport')}},"exportSessionHistoryCSV":{type:"click",call:(element,event)=>{invoke('exportSessionHistoryCSV')}},"focus-driver":{type:"click",call:(element,event)=>{invoke('focusDriver',element.dataset.driverArg)}},"handleHistoryToggle-event":{type:"toggle",call:(element,event)=>{invoke('handleHistoryToggle',event)}},"queueDriverListRender":{type:"change",call:(element,event)=>{invoke('queueDriverListRender')}},"refreshProtectedFleetNow":{type:"click",call:(element,event)=>{invoke('refreshProtectedFleetNow')}},"render":{type:"click",call:(element,event)=>{invoke('render')}},"renderPilotValue":{type:"change",call:(element,event)=>{invoke('renderPilotValue')}},"seedDemoData":{type:"click",call:(element,event)=>{invoke('seedDemoData')}}}),
"/fleet-onboarding.html":Object.freeze({"replaceInvite":{type:"click",call:(element,event)=>{invoke('resendInvite',encodeURIComponent(element.dataset.invitation))}},"revokeInvite":{type:"click",call:(element,event)=>{invoke('revokeInvite',encodeURIComponent(element.dataset.invitation))}},"copyInvite":{type:"click",call:(element,event)=>{invoke('copyInvite')}},"createFleet-event":{type:"submit",call:(element,event)=>{invoke('createFleet',event)}},"createInvite-event":{type:"submit",call:(element,event)=>{invoke('createInvite',event)}}}),
"/index.html":Object.freeze({"font-ready":{type:"load",call:(element,event)=>{element.media='all'}}}),
"/login.html":Object.freeze({"createProfilePasskey":{type:"click",call:(element,event)=>{invoke('createProfilePasskey')}},"finishPasskeySetup":{type:"click",call:(element,event)=>{invoke('finishPasskeySetup')}},"logout":{type:"click",call:(element,event)=>{invoke('logout')}},"retryProfileSync":{type:"click",call:(element,event)=>{invoke('retryProfileSync')}},"setRole-driver":{type:"click",call:(element,event)=>{invoke('setRole','driver')}},"setRole-fleet":{type:"click",call:(element,event)=>{invoke('setRole','fleet')}},"showAuthMode-email":{type:"click",call:(element,event)=>{invoke('showAuthMode','email')}},"showAuthMode-signin":{type:"click",call:(element,event)=>{invoke('showAuthMode','signin')}},"showAuthMode-signup":{type:"click",call:(element,event)=>{invoke('showAuthMode','signup')}},"signInPasskey":{type:"click",call:(element,event)=>{invoke('signInPasskey')}},"signInPasskey-true":{type:"click",call:(element,event)=>{invoke('signInPasskey',true)}},"submitAuth-event":{type:"submit",call:(element,event)=>{invoke('submitAuth',event)}}}),
"/pilot-signup.html":Object.freeze({"saveLead-event":{type:"submit",call:(element,event)=>{invoke('saveLead',event)}}}),
"/session-history.html":Object.freeze({"clearHistory":{type:"click",call:(element,event)=>{invoke('clearHistory')}},"render":{type:"click",call:(element,event)=>{invoke('render')}},"showCSV":{type:"click",call:(element,event)=>{invoke('showCSV')}}}),
};
const path=root.location.pathname==='/'?'/index.html':root.location.pathname;
const actions=routes[path];if(!actions)return;
function dispatch(event){const element=event.target?.closest?.('[data-page-action]');if(!element)return;if(!Object.hasOwn(actions,element.dataset.pageAction))return;const action=actions[element.dataset.pageAction];if(!action||action.type!==event.type)return;if(event.type==='submit'||event.type==='click')event.preventDefault();return action.call(element,event)}
for(const type of ['click','submit','change','input'])document.addEventListener(type,dispatch);
for(const type of ['toggle','load'])document.addEventListener(type,dispatch,true);
})(window);
