function cls(s){return s==='ALERT'||s==='HIGH'?'danger':s==='WATCH'?'watch':s==='SAFE'?'safe':''}
function readStored(key,fallback){try{return JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback))}catch(e){return fallback}}
function record(x){return x&&typeof x==='object'&&!Array.isArray(x)}
function getHistory(){let stored=readStored('occulert-session-history',[]),h=Array.isArray(stored)?stored.filter(record).slice(0,50):[];let live=readStored('occulert-live-session',null);if(record(live)&&!h.find(x=>(live.sessionId&&(x.id===live.sessionId||x.sessionId===live.sessionId))||(live.driverId&&live.lastUpdate&&x.driverId===live.driverId&&x.lastUpdate===live.lastUpdate)))h.unshift(live);return h.slice(0,50)}
function metric(value){if(value===null||value===undefined||typeof value==='boolean'||!['number','string'].includes(typeof value)||String(value).trim()==='')return null;const number=Number(value);return Number.isFinite(number)&&number>=0?number:null}
function count(value){return Math.floor(metric(value)||0)}
function score(value){const number=metric(value);return number===null?null:Math.min(100,number)}
function pct(n){return Math.max(0,Math.min(100,Number(n)||0))}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function csvCell(v){let text=String(v??'');if(/^[\s]*[=+\-@]|^[\t\r\n]/.test(text))text="'"+text;return '"'+text.split('"').join('""')+'"'}
function buildCSV(){let h=getHistory();let headers=['Driver Name','Driver ID','Status','Safety Score','Current Fatigue','Average Fatigue','Max Fatigue','Alerts','Head Nods','Confidence','Last Update','Saved At'];let rows=h.map(x=>[x.name||'Driver',x.driverId||'local',x.status||'NOT RECORDED',score(x.safetyScore)??'',x.fatigue??'',x.avgFatigue??'',x.maxFatigue??'',count(x.alerts),count(x.headNods),x.confidence??'',x.lastUpdate||'',x.savedAt||'']);return [headers.map(csvCell).join(','),...rows.map(r=>r.map(csvCell).join(','))].join('\n')}
function showCSV(){let h=getHistory();if(!h.length){alert('No sessions to export yet.');return}let box=document.getElementById('csvBox');box.value=buildCSV();box.style.display='block';box.focus();box.select();try{document.execCommand('copy');alert('CSV copied. You can paste it into Notes, Excel, or Google Sheets.')}catch(e){alert('CSV is ready to copy. Select the text box and copy it.')}}
function emptyState(){return '<div class="empty"><h2>No sessions saved yet</h2><p>Open the driver app, press Start Monitoring, stop the session, then return here to view a report.</p><div class="empty-actions"><a class="btn primary" href="/app.html">Launch Driver App</a><a class="btn" href="/fleet-dashboard.html">Open Fleet Dashboard</a></div></div>'}
function render(){let h=getHistory();document.getElementById('sessions').textContent=h.length;document.getElementById('alerts').textContent=h.reduce((a,x)=>a+(count(x.alerts)),0);document.getElementById('nods').textContent=h.reduce((a,x)=>a+(count(x.headNods)),0);document.getElementById('avgScore').textContent=(()=>{const scores=h.map(x=>score(x.safetyScore)).filter(x=>x!==null);return scores.length?Math.round(scores.reduce((a,x)=>a+x,0)/scores.length):'--'})();let t=document.getElementById('table');if(!h.length){t.innerHTML=emptyState();return}t.innerHTML='<div class="row" style="background:transparent;border:0;color:#94a3b8;font-size:12px;text-transform:uppercase;letter-spacing:1px"><div>Driver</div><div>Status</div><div>Safety</div><div>Fatigue</div><div>Alerts</div><div>Last Update</div></div>'+h.map(x=>`<div class="row"><div><strong>${esc(x.name||'Driver')}</strong><br><span class="small">${esc(x.driverId||'local')} · ${x.savedAt?'saved':'live/latest'}</span></div><div><span class="pill ${cls(x.status)}">${esc(x.status||'NOT RECORDED')}</span></div><div><strong>${esc(score(x.safetyScore)??'--')}</strong>/100<div class="scorebar"><span style="width:${pct(x.safetyScore)}%"></span></div></div><div><strong>${esc(x.avgFatigue??x.fatigue??0)}</strong> avg<br><span class="small">Max ${esc(x.maxFatigue??x.fatigue??0)}/100</span></div><div>${esc(count(x.alerts))} alerts<br><span class="small">${esc(count(x.headNods))} head nods</span></div><div>${esc(x.lastUpdate?new Date(x.lastUpdate).toLocaleString():(x.savedAt?new Date(x.savedAt).toLocaleString():'--'))}</div></div>`).join('')}
function clearHistory(){if(confirm('Clear local Occulert history on this browser?')){try{localStorage.removeItem('occulert-session-history');localStorage.removeItem('occulert-live-session');render()}catch(e){alert('Local history could not be fully cleared. Check browser storage access and try again.');render()}}}
render();setInterval(render,3000);
