function cls(s){return s==='ALERT'||s==='HIGH'?'danger':s==='WATCH'?'watch':'safe'}
function getHistory(){try{let h=JSON.parse(localStorage.getItem('occulert-session-history')||'[]');let live=JSON.parse(localStorage.getItem('occulert-live-session')||'null');if(live&&!h.find(x=>x.driverId===live.driverId&&x.lastUpdate===live.lastUpdate))h.unshift(live);return h}catch(e){return[]}}
function pct(n){return Math.max(0,Math.min(100,Number(n)||0))}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function csvCell(v){return '"'+String(v??'').split('"').join('""')+'"'}
function buildCSV(){let h=getHistory();let headers=['Driver Name','Driver ID','Status','Safety Score','Current Fatigue','Average Fatigue','Max Fatigue','Alerts','Head Nods','Confidence','Last Update','Saved At'];let rows=h.map(x=>[x.name||'Driver',x.driverId||'local',x.status||'SAFE',x.safetyScore??'',x.fatigue??'',x.avgFatigue??'',x.maxFatigue??'',x.alerts||0,x.headNods||0,x.confidence??'',x.lastUpdate||'',x.savedAt||'']);return [headers.map(csvCell).join(','),...rows.map(r=>r.map(csvCell).join(','))].join('\n')}
function showCSV(){let h=getHistory();if(!h.length){alert('No sessions to export yet.');return}let box=document.getElementById('csvBox');box.value=buildCSV();box.style.display='block';box.focus();box.select();try{document.execCommand('copy');alert('CSV copied. You can paste it into Notes, Excel, or Google Sheets.')}catch(e){alert('CSV is ready to copy. Select the text box and copy it.')}}
function emptyState(){return '<div class="empty"><h2>No sessions saved yet</h2><p>Open the driver app, press Start Monitoring, stop the session, then return here to view a report.</p><div class="empty-actions"><a class="btn primary" href="/app.html">Launch Driver App</a><a class="btn" href="/fleet-dashboard.html">Open Fleet Dashboard</a></div></div>'}
function render(){let h=getHistory();document.getElementById('sessions').textContent=h.length;document.getElementById('alerts').textContent=h.reduce((a,x)=>a+(x.alerts||0),0);document.getElementById('nods').textContent=h.reduce((a,x)=>a+(x.headNods||0),0);document.getElementById('avgScore').textContent=h.length?Math.round(h.reduce((a,x)=>a+(x.safetyScore||0),0)/h.length):'--';let t=document.getElementById('table');if(!h.length){t.innerHTML=emptyState();return}t.innerHTML='<div class="row" style="background:transparent;border:0;color:#94a3b8;font-size:12px;text-transform:uppercase;letter-spacing:1px"><div>Driver</div><div>Status</div><div>Safety</div><div>Fatigue</div><div>Alerts</div><div>Last Update</div></div>'+h.map(x=>`<div class="row"><div><strong>${esc(x.name||'Driver')}</strong><br><span class="small">${esc(x.driverId||'local')} · ${x.savedAt?'saved':'live/latest'}</span></div><div><span class="pill ${cls(x.status)}">${esc(x.status||'SAFE')}</span></div><div><strong>${esc(x.safetyScore??'--')}</strong>/100<div class="scorebar"><span style="width:${pct(x.safetyScore)}%"></span></div></div><div><strong>${esc(x.avgFatigue??x.fatigue??0)}</strong> avg<br><span class="small">Max ${esc(x.maxFatigue??x.fatigue??0)}/100</span></div><div>${esc(x.alerts||0)} alerts<br><span class="small">${esc(x.headNods||0)} head nods</span></div><div>${esc(x.lastUpdate?new Date(x.lastUpdate).toLocaleString():(x.savedAt?new Date(x.savedAt).toLocaleString():'--'))}</div></div>`).join('')}
function clearHistory(){if(confirm('Clear local Occulert history on this browser?')){localStorage.removeItem('occulert-session-history');localStorage.removeItem('occulert-live-session');render()}}
render();setInterval(render,3000);
